-- MySQL Script generated by MySQL Workbench
-- Sun Oct 15 14:26:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smartpass
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smartpass

-- -----------------------------------------------------
drop database if EXISTS smartpass;
CREATE SCHEMA IF NOT EXISTS `smartpass` DEFAULT CHARACTER SET utf8 ;
USE `smartpass` ;

-- -----------------------------------------------------
-- Table `smartpass`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartpass`.`usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(250) NULL,
  `senha` VARCHAR(100) NULL,
  `token` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartpass`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartpass`.`cliente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` INT UNSIGNED NULL,
  `nome` VARCHAR(100) NULL,
  `saldo` DECIMAL(8,2) NULL,
  `cpf` CHAR(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `smartpass`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartpass`.`linha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartpass`.`linha` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `origem` VARCHAR(100) NULL,
  `destino` VARCHAR(100) NULL,
  `horarioPartida` TIME NULL,
  `duracao` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartpass`.`motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartpass`.`motorista` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `foto` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartpass`.`onibus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartpass`.`onibus` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `placa` CHAR(7) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartpass`.`viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartpass`.`viagem` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `linha_id` INT UNSIGNED NULL,
  `motorista_id` INT UNSIGNED NULL,
  `onibus_id` INT UNSIGNED NULL,
  `dataPartida` DATETIME NULL,
  `dataChegada` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_viagem_linha1_idx` (`linha_id` ASC),
  INDEX `fk_viagem_motorista1_idx` (`motorista_id` ASC),
  INDEX `fk_viagem_onibus1_idx` (`onibus_id` ASC),
  CONSTRAINT `fk_viagem_linha1`
    FOREIGN KEY (`linha_id`)
    REFERENCES `smartpass`.`linha` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_motorista1`
    FOREIGN KEY (`motorista_id`)
    REFERENCES `smartpass`.`motorista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_onibus1`
    FOREIGN KEY (`onibus_id`)
    REFERENCES `smartpass`.`onibus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartpass`.`embarque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartpass`.`embarque` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cliente_id` INT UNSIGNED NULL,
  `viagem_id` INT UNSIGNED NULL,
  `tarifa` DECIMAL(8,2) NULL,
  `horario` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_has_viagem_viagem1_idx` (`viagem_id` ASC),
  INDEX `fk_cliente_has_viagem_cliente1_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_cliente_has_viagem_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `smartpass`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_viagem_viagem1`
    FOREIGN KEY (`viagem_id`)
    REFERENCES `smartpass`.`viagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
